version: "3.9"

services:

  seafile-mariadb:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_LOG_CONSOLE=true
    env_file:
      - .seafile.env
    volumes:
      - ./seafile/mariadb:/var/lib/mysql
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

  seafile-memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    volumes:
      - ./seafile/seafile:/shared   # Requested, specifies the path to Seafile data persistent store.
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOST=seafile-mariadb
      - SEAFILE_SERVER_HOSTNAME=seafile.${BASE_DOMAIN}
    env_file:
      - .seafile.env
    depends_on:
      - seafile-mariadb
      - seafile-memcached
    networks:
      - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.seafile.rule=Host(`seafile.${BASE_DOMAIN}`)"
        - "traefik.http.routers.seafile.entrypoints=websecure"
        - "traefik.http.routers.seafile.tls=true"
        - "traefik.http.routers.seafile.tls.certresolver=cloudflare"
        - "traefik.http.routers.seafile.service=seafile"
        - "traefik.http.services.seafile.loadbalancer.server.port=80"


networks:
  traefik:
    external: true