version: "3.9"

services:

    siyuan:
      image: b3log/siyuan
      container_name: siyuan
      restart: unless-stopped
      command: [ '--workspace=/siyuan/workspace/', '--accessAuthCode=${AuthCode}' ]
      user: '1000:1000'
      volumes:
        - ./siyuan:/siyuan/workspace
        - /etc/localtime:/etc/localtime:ro
      environment:
        - TZ=Asia/Shanghai
        - AuthCode=123456
      networks:
        - traefik
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.siyuan.rule=Host(`siyuan.${BASE_DOMAIN}`)"
        - "traefik.http.routers.siyuan.entrypoints=websecure"
        - "traefik.http.routers.siyuan.tls.certresolver=cloudflare"
        - "traefik.http.routers.siyuan.tls=true"
        - "traefik.http.routers.siyuan.service=siyuan"
        - "traefik.http.services.siyuan.loadbalancer.server.port=6806"

networks:
  traefik:
    external: true